version: '3.8'

services:
  mongodb:
    image: mongo:5.0  # Updated MongoDB image version
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb_volume:/data/db
    restart: always
    command: --bind_ip 0.0.0.0 --port 27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  ramsey-api:
    build:
      context: ./api  # Adjust the path to where your Dockerfile is located
      dockerfile: Dockerfile
    container_name: ramsey-api
    ports:
      - "3000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always
    environment:
      - FLASK_APP=server.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend  # Adjust the path to where your Angular frontend Dockerfile is located
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - "80:4200"  # Internal port used by the frontend service
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`34.172.128.64`)"  # Use your IP address
      - "traefik.http.routers.frontend.entrypoints=websecure"

volumes:
  traefik-certificates:
