# Exported from Render on 2024-10-26T00:16:49Z
services:
- type: web
  name: RamseyChess
  runtime: docker
  repo: https://github.com/daniel117622/RamseyChess
  plan: free
  envVars:
  - key: RAMSEY_API_PORT
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
